repository:
  name: Productividad
  default_branch: dev
  allow_merge_commit: false
  allow_squash_merge: true
  allow_rebase_merge: true

branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts:
          - lint
          - test
      enforce_admins: true
      required_pull_request_reviews:
        required_approving_review_count: 1
      restrictions: null
      required_linear_history: true
      allow_force_pushes: false
      allow_deletions: false

  - name: dev
    protection:
      required_status_checks:
        strict: true
        contexts:
          - lint
          - test
      enforce_admins: true
      required_pull_request_reviews: null
      restrictions: null
      required_linear_history: false
      allow_force_pushes: false
      allow_deletions: false

  - name: 'feature/*'
    protection:
      required_status_checks:
        strict: false
        contexts: []
      enforce_admins: false
      required_pull_request_reviews: null
      restrictions: null
      allow_force_pushes: false
      allow_deletions: false

  - name: 'bugfix/*'
    protection:
      required_status_checks:
        strict: false
        contexts: []
      enforce_admins: false
      required_pull_request_reviews: null
      restrictions: null
      allow_force_pushes: false
      allow_deletions: false
      
  - name: 'hotfix/*'
    protection:
      required_status_checks:
        strict: false
        contexts: []
      enforce_admins: false
      required_pull_request_reviews: null
      restrictions: null
      allow_force_pushes: false
      allow_deletions: false
